name: waktusolatmalaysia
description: App waktu solat seluruh Malaysia

publish_to: "none"

version: 1.3.1-web+12

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  intl: ^0.17.0
  google_fonts: ^2.1.0
  fluttertoast: ^8.0.7
  hijri:
    git: https://github.com/iqfareez/hijri_date.git
  get_storage: ^2.0.2
  url_launcher: ^6.0.4
  flutter_spinkit: ^5.0.0
  get: ^4.1.4
  auto_size_text: ^2.1.0
  provider: ^5.0.0
  font_awesome_flutter: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
