name: waktusolatmalaysia
description: App waktu solat seluruh Malaysia

publish_to: "none"

version: 1.0.4-web+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2
  intl: ^0.16.1
  google_fonts: ^1.1.0
  fluttertoast: ^7.0.2
  hijri:
    git: git://github.com/iqfareez/hijri_date.git
  get_storage: ^1.3.0
  url_launcher: ^5.5.1
  flutter_spinkit: ^4.1.2+1
  get: ^3.12.1
  flutter_svg: ^0.19.2+1
  auto_size_text: ^2.1.0
  provider: ^4.3.2+2
  font_awesome_flutter: ^8.11.0
  # cloud_firestore: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
